### ISSUE TITLE
Not working in FW 2.1.0

### ISSUE THREAD

**Issue by lorenzo93** [xMase/Sercomm-VD625#1]
Hi,

just tried this with my modem, firmware 2.1.0 (bootloader 1.04.0).
I was able to access the SMB root share but unable to modify any file.
I've tried logging both with admin:mysecretpassword and with root:root without any success.
Also for the curl request I didn't succeed with your line but I needed to create a request with all the cookies set in the browser.

Is there another trick to change the smb config file?

**Comment by xMase** [comment]
![immagine](https://user-images.githubusercontent.com/11925311/64074459-c8b09380-ccab-11e9-880b-c6aeaa87f2b0.png)

try this file

**Comment by lorenzo93** [comment]
I already tried to change that file (the file you mentioned in the guide is a symlink to that file) without any success.
I don't know if they changed something in the configuration to disable the way SMB shares folders

**Comment by FrancYescO** [comment]
https://www.ilpuntotecnico.com/forum/index.php/topic,80664.msg260569.html#msg260569
