### ISSUE TITLE
can't find the /etc/samba/smb.conf folder

### ISSUE THREAD

**Issue by giorgionegro** [xMase/Sercomm-VD625#2]
i insert the usb and use the curl command but i can't find  the /etc/samba/smb.conf folder in windows

**Comment by xMase** [comment]
[https://www.ilpuntotecnico.com/forum/index.php/topic,80664.msg260569.html#msg260569](https://www.ilpuntotecnico.com/forum/index.php/topic,80664.msg260569.html#msg260569)
