### ISSUE TITLE
cannot enable sharing

### ISSUE THREAD

**Issue by ghost** [xMase/Sercomm-VD625#4]
$ curl -X POST -i 'http://192.168.1.1/data/settings_network_sharing.json?_=1635699039535&csrf_token=HK49DEFD49JW18DF93EF' --data 'sharing_device=[{"device_id":"1","root_folder":"/","ns_content_sharing_enable":"1","ns_require_username_password":"0","ns_user_id":"1","ns_share_all_folders":"0","ns_share_folder_data":"1|root|../../../:0|Partition1|:"}]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   271    0    51  100   220    419   1808 --:--:-- --:--:-- --:--:--  2277HTTP/1.0 200 OK
Content-Type: text/html
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; report=http://www.example.com/xss

<script> top.location.href="/login.html"; </script>

**Comment by xMase** [comment]
what firmware version do you have?

**Comment by ghost** [comment]
Thank you for replying.
I have two vd625 routers with 1.0.4 and 1.0.9 fw and i 
am facing the same problem..
I am using Google Chrome on Windows..

**Comment by ghost** [comment]
I am a non-TIM client..
Unlocking the router is my main purpose..is there a way to unlock it without rooting..
Thanks for the help..

**Comment by ghost** [comment]
Still need your precious help xMase..
Thank you..

**Comment by ghost** [comment]
Thank you very much..
