### ISSUE TITLE
Not working in FW AGSOT_1.0.4

### ISSUE THREAD

**Issue by fra-pel** [xMase/Sercomm-VD625#5]
My router:
Firmware versionAGSOT_1.0.4
Bootloader Version1.04.0
Hardware Type & VersionV01

The guide (with this support: https://www.ilpuntotecnico.com/forum/index.php/topic,80664.msg260569.html#msg260569) work, but i can't remove /tmp/samba/smb.conf
![image](https://github.com/xMase/Sercomm-VD625/assets/18364456/eb50ffa6-9b9b-46fd-8294-5ff17216a044)
I tried to mount the directory as admin:admin and as root:root but no luck.

Have an idea?
How can i update the firmware? i
I need the unlock to be able to change voip configurations that are locked.

Thanks

**Comment by xMase** [comment]
You have 1.0.4 firmware on your modem, so you must use the guide on this repo (for samba step).

* samba process was spawned with the user nobody who does not have root privileges, to remedy this, **replace the router /etc/samba/smb.conf file with the one in the shared folder on the usb key**

Why do you want to remove **smb.conf** from **/mnt/tmp/samba** folder?

Sorry i cant help you much, i dont have this modem anymore.

**Comment by fra-pel** [comment]
Thanks for the answer.

I tried to delete or replace in /tmp/samba becuse it'a sym link of /etc/samba:
![image](https://github.com/xMase/Sercomm-VD625/assets/18364456/b4be3805-9499-47c4-9b1e-9c785fae740b)
but i can't replace the same.

Thanks anyway :)

**Comment by xMase** [comment]
can you give me the result of **whoami** command?

It sounds like you already have telnet with root access (somehow) and therefore don't need to do the samba switch
